# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yelp_Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest1', models.CharField(max_length=200)),
                ('rest2', models.CharField(max_length=200)),
                ('rest3', models.CharField(max_length=200)),
                ('rest4', models.CharField(max_length=200)),
                ('rest5', models.CharField(max_length=200)),
                ('choice_text', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
