# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
